name: "Setup GitHub App Tokens"
description: "Setup GitHub App tokens for Supplement-Bacon and Paris-Society"

inputs:
  app_id:
    required: true
    description: "GitHub App ID"
  private_key:
    required: true
    description: "GitHub App private key"

outputs:
  token:
    description: "GitHub App token for Supplement-Bacon"
    value: ${{ steps.app-token.outputs.token }}
  token-paris:
    description: "GitHub App token for Paris-Society"
    value: ${{ steps.app-token-paris.outputs.token }}

runs:
  using: composite
  steps:
    - name: Generate GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        repositories: |
          table-booking-back-office-api
          laravel-trivec
          laravel-paginable
          laravel-api-toolkit
        owner: Supplement-Bacon

    - name: Generate GitHub App token for Paris-Society
      id: app-token-paris
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app_id }}
        private-key: ${{ inputs.private_key }}
        repositories: table-booking-backend
        owner: Paris-Society
