name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      DOMAIN:
        required: true
        type: string
      SSH_PRIVATE_KEY:
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: forge-deploy-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  forge:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ inputs.SSH_PRIVATE_KEY }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none

      - name: Install Forge CLI
        run: composer global require laravel/forge-cli

      - name: Deploy
        run: forge deploy ${{ inputs.DOMAIN }}
        env:
          FORGE_API_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
