name: Laravel Pint

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      extra_owner:
        required: false
        type: string
        default: ""
      extra_repositories:
        required: false
        type: string
        default: ""

permissions:
  contents: write

jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BACKEND_CI_DEPENDENCIES_APP_ID }}
          private-key: ${{ secrets.BACKEND_CI_DEPENDENCIES_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ inputs.repository }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup PHP & Composer
        uses: Supplement-Bacon/.github/.github/actions/php@main
        with:
          app_id: ${{ secrets.BACKEND_CI_DEPENDENCIES_APP_ID }}
          private_key: ${{ secrets.BACKEND_CI_DEPENDENCIES_APP_PRIVATE_KEY }}
          extra_owner: ${{ inputs.extra_owner }}
          extra_repositories: ${{ inputs.extra_repositories }}

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Commit changes
        if: github.event_name == 'pull_request'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: fix code formatting with Laravel Pint"
          branch: ${{ github.head_ref }}
