name: Coverage

on:
  workflow_call:
    inputs:
      composer_repositories:
        required: false
        type: string
      extra_owner:
        required: false
        type: string
        default: ""
      extra_repositories:
        required: false
        type: string
        default: ""

permissions:
  contents: read
  pull-requests: write

jobs:
  factory-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Setup PHP & Composer
        uses: Supplement-Bacon/.github/.github/actions/setup-php-and-dependencies@feat/ci-back
        with:
          app_id: ${{ secrets.BACKEND_CI_DEPENDENCIES_APP_ID }}
          private_key: ${{ secrets.BACKEND_CI_DEPENDENCIES_APP_PRIVATE_KEY }}
          repositories: ${{ inputs.composer_repositories }}
          extra_owner: ${{ inputs.extra_owner }}
          extra_repositories: ${{ inputs.extra_repositories }}

      - name: Run Factory Coverage command
        id: factory_coverage
        continue-on-error: true
        run: |
          php vendor/bin/testbench model:factory-coverage --markdown > factory-coverage.txt

          echo "coverage<<EOF" >> $GITHUB_OUTPUT
          cat factory-coverage.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          mode: upsert
          comment-tag: "model-factory-coverage"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ## 🧪 Model / Factory Coverage

            ${{ steps.factory_coverage.outputs.coverage }}
